### ISSUE TITLE
READMEにHerokuのデプロイボタンを付ける

### ISSUE THREAD

**Issue by massongit** [kons16/ClassDeru#13]
READMEにHerokuのデプロイボタンを付けると良いかも知れません。
https://jp.heroku.com/elements/buttons

**Comment by massongit** [comment]
21b0b6f81a175e79ad4fc28d4012c09fe92693b1 で実現していることを確認しました。
ちなみに、コミットメッセージやPRのタイトルを使って、Issueを閉じることができます: [コミット時にIssueをCloseする - Qiita](https://qiita.com/maeda_t/items/d9ef98bf651bd491b16d)

**Comment by kons16** [comment]
了解です。

**Comment by massongit** [comment]
また、『Issueを閉じるつもりはないが、コミット (PR) をIssueに紐づけたい』という場合には、単純にIssueの番号 (`#123`) をコミットメッセージ (タイトル) に含めると紐付けられます。
