### ISSUE TITLE
Docker上で動かせるようにする

### ISSUE THREAD

**Issue by massongit** [kons16/ClassDeru#21]
Docker上で動かせるようになれば、ローカル上で動かせるようになり、Herokuへのデプロイ手順も今より簡略化されるかもしれません。

**Comment by massongit** [comment]
@kons16 このアプリのサブモジュールとして使いたいので、[laradock](https://github.com/laradock/laradock) (Laravel用のDockerイメージ) をforkしていただいても良いでしょうか？ (この際、名前もこのアプリのサブモジュールだと分かるように変更すると良いかも知れません)

**Comment by massongit** [comment]
https://github.com/kons16/classderu_sub_laradock/ にCollaboratorとして追加していただけると助かります。

**Comment by kons16** [comment]
了解です。
