### ISSUE TITLE
出席ボタンをクリックすると500 (Internal Server Error) になる

### ISSUE THREAD

**Issue by massongit** [kons16/ClassDeru#30]
`resources/views/lectures.blade.php`から`resources/views/common/_script.blade.php`を参照できていないのが原因の一つですが、それ以外にも原因がありそうです。

**Comment by massongit** [comment]
`resources/views/lectures.blade.php`から`resources/views/common/_script.blade.php` を参照できていない現象は https://classderu.herokuapp.com/ でも発生していますが、こちらですと500にはならないようです (Docker上で動かすと500になります)。

**Comment by kons16** [comment]
今みたところ、https://classderu.herokuapp.com/ でも500になってます

**Comment by massongit** [comment]
最新のコミットをデプロイしてみました。

**Comment by kons16** [comment]
確認しましたー
